controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_endpoints:
    path: /api/email-report
    controller: App\Controller\Api\ReportController::index
    methods: ['POST']